"use client";

import { useMemo, useState } from "react";
import { IconCalendar, IconCustomer, IconOrder } from "../preview-icons";
import { PreviewBottomSheet, PreviewButton, PreviewCard, PreviewNotice, PreviewPill, PreviewState, PreviewToast, SectionTitle } from "../preview-ui";
import { formatBusinessDate } from "@/lib/domain/time";
import { formatCurrentDateTime, formatLongDate, formatServiceDate, formatShortDate, isMealCutoffPassed, mealCutoff, mealLabel, type MealCode, type PlanType, usePreviewStore } from "../preview-store";

type CustomerTab = "menu" | "orders" | "account";

export interface CustomerPlanState { name: string; type: PlanType; coverageSummary: string; renewalDate: string; }

const customerId = "CUS-011";
const meals: MealCode[] = ["BREAKFAST", "LUNCH", "DINNER"];
const datePart = (date: string, part: "weekday" | "day") => formatBusinessDate(date, { [part]: part === "weekday" ? "short" : "numeric" });

export function CustomerPreview() {
  const store = usePreviewStore();
  const customer = store.getCustomer(customerId)!;
  const [tab, setTab] = useState<CustomerTab>("menu");
  const [selectedDate, setSelectedDate] = useState(store.today);
  const [reviewMeal, setReviewMeal] = useState<MealCode | null>(null);
  const [cancelId, setCancelId] = useState<string | null>(null);
  const [showPlanPicker, setShowPlanPicker] = useState(false);
  const [showStatement, setShowStatement] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const selectedDay = store.serviceDays.find((day) => day.date === selectedDate)!;
  const canOrder = selectedDay.state === "published";
  const upcoming = useMemo(() => store.orders.filter((order) => order.customerId === customerId && order.status === "CONFIRMED" && order.serviceDate >= store.today), [store.orders, store.today]);
  const history = useMemo(() => store.orders.filter((order) => order.customerId === customerId && !(order.status === "CONFIRMED" && order.serviceDate >= store.today)), [store.orders, store.today]);
  const statement = useMemo(() => store.ledger.filter((entry) => entry.customerId === customerId), [store.ledger]);
  const statementBalance = statement.reduce((total, entry) => total + entry.amount, 0);

  function confirmOrder() {
    if (!reviewMeal) return;
    setSaving(true);
    window.setTimeout(() => {
      const result = store.placeOrder({ customerId, serviceDate: selectedDate, meal: reviewMeal, source: "CUSTOMER" });
      setSaving(false);
      if (!result.ok) { setError(result.message); return; }
      setReviewMeal(null);
      setMessage(result.message);
    }, 250);
  }

  function cancelOrder(id: string) {
    const result = store.cancelOrder(id);
    setCancelId(null);
    result.ok ? setMessage(result.message) : setError(result.message);
  }

  function choosePlan(planType: PlanType) {
    store.changeCustomerPlan(customerId, planType);
    setShowPlanPicker(false);
    setMessage(planType === "ONE_TIME" ? "You are now on pay as you order. Every future booking shows its charge first." : "Plan updated. The visible meal balance is ready to use.");
  }

  return <div className="relative space-y-6 pb-20">
    {tab === "menu" ? <>
      <section className="service-strip rounded-3xl p-5 shadow-sm sm:p-6">
        <span className="inline-block rounded-full bg-[var(--saffron-pale)] px-3 py-1 text-xs font-black text-[var(--saffron-deep)]">{customer.planType === "ONE_TIME" ? "Pay as you order" : customer.planName}</span>
        <h1 className="mt-2 text-2xl font-black tracking-tight text-stone-900 sm:text-3xl">Good morning, Aarav</h1>
        <p className="mt-1 text-sm leading-relaxed text-stone-600">Choose a date, see whether it is covered, then book. Current time: {formatCurrentDateTime(store.now)}.</p>
      </section>
      <section className="space-y-3">
        <SectionTitle eyebrow="Choose a date" title="Meal schedule" detail="Today, future dates, cutoffs and closures all use the same prototype clock." />
        <div className="flex gap-2 overflow-x-auto pb-2" aria-label="Service dates">
          {store.serviceDays.map((day) => { const selected = day.date === selectedDate; return <button key={day.date} type="button" onClick={() => { setSelectedDate(day.date); setError(null); }} aria-pressed={selected} className={`min-w-20 shrink-0 rounded-2xl border px-3 py-3 text-center text-xs font-extrabold ${selected ? "border-[var(--saffron)] bg-[var(--saffron)] text-white" : "border-stone-200 bg-white text-stone-700"}`}><span className="block text-[11px] opacity-75">{datePart(day.date, "weekday")}</span><span className="block text-lg font-black">{datePart(day.date, "day")}</span><span className="block text-[10px]">{day.date === store.today ? "Today" : day.state === "closed" ? "Closed" : day.state === "unpublished" ? "Awaiting menu" : day.state === "past" ? "Past" : "Open"}</span></button>; })}
        </div>
      </section>
      {selectedDay.state === "unpublished" ? <PreviewState kind="empty" title="Menu is not published yet" detail={`The kitchen has not published ${formatLongDate(selectedDate)}. You cannot book until it is published.`} /> : null}
      {selectedDay.state === "closed" ? <PreviewState kind="error" title="No food service on this date" detail="This day is closed. Any eligible booked meals are returned or credited when the closure is confirmed." /> : null}
      {selectedDay.state === "past" ? <PreviewState kind="error" title="This service date has passed" detail="Orders are kept in history after service. The kitchen cutoff is no longer available." /> : null}
      {canOrder ? <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-lg font-black text-stone-900">Menu for {formatServiceDate(selectedDate)}</h2><span className="text-xs font-bold text-stone-500">Choose before cutoff</span></div>{meals.map((meal) => { const coverage = store.getCoverage(customerId, meal); const cutoffPassed = isMealCutoffPassed(meal, selectedDate, store.now); const booked = store.orders.some((order) => order.customerId === customerId && order.serviceDate === selectedDate && order.meal === meal && order.status === "CONFIRMED"); return <PreviewCard key={meal} className="space-y-3"><div className="flex justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-stone-500">{mealLabel(meal)} · cutoff {mealCutoff(meal)}</p><h3 className="mt-1 text-base font-black text-stone-900">{store.getMenuDish(selectedDate, meal)}</h3></div><p className="text-lg font-black text-stone-900">₹{store.prices[meal]}</p></div><div className="flex flex-wrap items-center justify-between gap-2 border-t border-stone-100 pt-3"><span className={`rounded-lg border px-2.5 py-1 text-xs font-extrabold ${coverage.covered ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-amber-200 bg-amber-50 text-amber-800"}`}>{coverage.covered ? coverage.message : `Not covered — ₹${coverage.amount} will be added to your balance`}</span>{booked ? <PreviewPill tone="ready">Booked</PreviewPill> : cutoffPassed ? <PreviewPill tone="danger">Cutoff passed</PreviewPill> : <PreviewButton className="min-h-10 px-3 text-xs" variant={coverage.covered ? "primary" : "secondary"} onClick={() => { setError(null); setReviewMeal(meal); }}>Review order</PreviewButton>}</div>{cutoffPassed ? <p className="text-xs text-stone-500">{mealLabel(meal)} ordering closed at {mealCutoff(meal)} so the kitchen can lock its preparation list.</p> : null}</PreviewCard>; })}</section> : null}
      <section className="grid grid-cols-2 gap-3"><PreviewCard className="p-4"><p className="text-xs font-extrabold uppercase text-stone-500">Available meals</p><p className="mt-1 text-2xl font-black text-stone-900">{customer.lunches + customer.dinners}</p><p className="text-xs text-stone-500">{customer.lunches} lunches · {customer.dinners} dinners</p></PreviewCard><PreviewCard className="p-4"><p className="text-xs font-extrabold uppercase text-stone-500">You owe</p><p className="mt-1 text-2xl font-black text-stone-900">₹{customer.outstanding}</p><button type="button" onClick={() => setTab("account")} className="text-xs font-extrabold text-[var(--saffron-deep)]">See statement</button></PreviewCard></section>
    </> : null}

    {tab === "orders" ? <section className="space-y-5"><SectionTitle eyebrow="Your bookings" title="Upcoming orders" detail="Only confirmed meals on or after today count here. Completed and cancelled meals remain in history." />{upcoming.length === 0 ? <PreviewState kind="empty" title="No upcoming meals" detail="Choose a published future date from Menu to book your next meal." /> : upcoming.map((order) => <PreviewCard key={order.id} accent="saffron" className="space-y-3"><div className="flex justify-between gap-3"><div><p className="text-xs font-black uppercase text-stone-400">{order.id}</p><h3 className="font-black text-stone-900">{mealLabel(order.meal)} · {formatServiceDate(order.serviceDate)}</h3><p className="text-xs text-stone-600">{order.dish}</p></div><PreviewPill tone="ready">Confirmed</PreviewPill></div><div className="flex flex-wrap items-center justify-between gap-2 border-t border-stone-100 pt-3"><span className="text-xs font-bold text-emerald-700">{order.covered ? "Covered by your plan" : `₹${order.amount} added to your balance`}</span><PreviewButton variant="outline" className="min-h-10 border-red-200 px-3 text-xs text-red-700 hover:bg-red-50" onClick={() => setCancelId(order.id)}>Cancel meal</PreviewButton></div>{cancelId === order.id ? <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-950"><p className="font-black">Cancel before {mealCutoff(order.meal)}?</p><p className="mt-1">{order.covered ? "One meal returns to available meals and appears below as a returned meal. You do not lose it." : `₹${order.amount} is credited from your balance.`}</p><div className="mt-3 flex gap-2"><PreviewButton variant="secondary" className="min-h-9 flex-1 px-3 text-xs" onClick={() => setCancelId(null)}>Keep booking</PreviewButton><PreviewButton variant="danger" className="min-h-9 flex-1 px-3 text-xs" onClick={() => cancelOrder(order.id)}>Confirm cancellation</PreviewButton></div></div> : null}</PreviewCard>)}<section className="space-y-3 border-t border-stone-200 pt-5"><h2 className="text-sm font-extrabold uppercase tracking-wider text-stone-500">History</h2>{history.length === 0 ? <p className="text-sm text-stone-500">No past meal activity yet.</p> : history.map((order) => <PreviewCard key={order.id} accent={order.status === "CANCELLED" ? "danger" : undefined} className="flex items-start justify-between gap-3"><div><h3 className="font-black text-stone-900">{mealLabel(order.meal)} · {formatServiceDate(order.serviceDate)}</h3><p className="text-xs text-stone-600">{order.status === "CANCELLED" ? order.cancellationNote || "Cancelled" : order.dish}</p></div><PreviewPill tone={order.status === "CANCELLED" ? "danger" : "neutral"}>{order.status === "COMPLETED" ? "Delivered" : "Cancelled"}</PreviewPill></PreviewCard>)}</section></section> : null}

    {tab === "account" ? <section className="space-y-5"><SectionTitle eyebrow="Your account" title="Plan, meals & balance" detail="Every number below is connected to your orders and statement." action={<button type="button" onClick={() => setShowPlanPicker(true)} className="text-xs font-extrabold text-[var(--saffron-deep)]">Change plan</button>} /><PreviewCard className="space-y-3"><div className="flex justify-between gap-3"><div><p className="text-xs font-extrabold uppercase text-stone-500">Current plan</p><h2 className="text-lg font-black text-stone-900">{customer.planName}</h2></div><PreviewPill tone="ready">Active</PreviewPill></div>{customer.planType === "ONE_TIME" ? <PreviewNotice tone="amber">Each meal shows its price before you confirm. There is no prepaid balance or carry-forward benefit on this plan.</PreviewNotice> : <div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-stone-50 p-3"><p className="text-xs font-bold text-stone-500">Lunches available</p><p className="text-2xl font-black text-stone-900">{customer.lunches}</p></div><div className="rounded-xl bg-stone-50 p-3"><p className="text-xs font-bold text-stone-500">Dinners available</p><p className="text-2xl font-black text-stone-900">{customer.dinners}</p></div></div>}</PreviewCard>{customer.planType !== "ONE_TIME" && (customer.carriedForwardLunches > 0 || customer.returnedLunches > 0 || customer.reservedLunches > 0) ? <PreviewCard className="space-y-2"><h2 className="font-black text-stone-900">Meal detail</h2>{customer.carriedForwardLunches > 0 ? <p className="text-sm text-stone-700"><strong>{customer.carriedForwardLunches} lunches carried forward</strong> from the previous plan period.</p> : null}{customer.returnedLunches > 0 ? <p className="text-sm text-stone-700"><strong>{customer.returnedLunches} returned lunch{customer.returnedLunches === 1 ? "" : "es"}</strong> came back from an eligible cancellation and are included above.</p> : null}{customer.reservedLunches > 0 && customer.reservationStartsOn ? <p className="text-sm text-stone-700"><strong>{customer.reservedLunches} lunches reserved</strong> from {formatLongDate(customer.reservationStartsOn)}. They become available on that date, not today.</p> : null}</PreviewCard> : null}<PreviewCard className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase text-stone-500">Outstanding balance</p><p className="text-sm text-stone-600">Charges minus payments and credits</p></div><div className="text-right"><p className="text-2xl font-black text-stone-900">₹{customer.outstanding}</p><button type="button" onClick={() => setShowStatement(true)} className="text-xs font-extrabold text-[var(--saffron-deep)]">View statement</button></div></PreviewCard></section> : null}

    <nav aria-label="Customer navigation" className="fixed bottom-0 left-0 right-0 z-30 border-t border-stone-200 bg-white/95 px-3 py-2 backdrop-blur-md"><div className="mx-auto flex max-w-md justify-around">{([{ id: "menu", label: "Menu", icon: IconCalendar }, { id: "orders", label: `Orders (${upcoming.length})`, icon: IconOrder }, { id: "account", label: "Account", icon: IconCustomer }] as const).map((item) => { const Icon = item.icon; const active = item.id === tab; return <button key={item.id} type="button" onClick={() => setTab(item.id)} aria-current={active ? "page" : undefined} className={`flex min-h-12 flex-1 flex-col items-center justify-center rounded-xl text-xs font-extrabold ${active ? "bg-[var(--saffron-pale)] text-[var(--saffron-deep)]" : "text-stone-500"}`}><Icon className="size-5" />{item.label}</button>; })}</div></nav>

    {reviewMeal ? <PreviewBottomSheet title="Review meal order" onClose={() => setReviewMeal(null)}><div className="space-y-4">{(() => { const coverage = store.getCoverage(customerId, reviewMeal); return <><PreviewNotice tone={coverage.covered ? "green" : "amber"}><p className="font-black">{mealLabel(reviewMeal)} · {formatServiceDate(selectedDate)}</p><p className="mt-1">{store.getMenuDish(selectedDate, reviewMeal)}</p><p className="mt-2 font-bold">{coverage.covered ? coverage.message : `₹${coverage.amount} will be added to your outstanding balance.`}</p></PreviewNotice><p className="text-sm text-stone-600">Cancel before {mealCutoff(reviewMeal)} and {coverage.covered ? "the meal returns to your available meals" : "the charge is credited"}.</p></>; })()}{error ? <PreviewState kind="error" title="Order not created" detail={error} /> : null}<div className="flex gap-2"><PreviewButton variant="secondary" className="flex-1" onClick={() => setReviewMeal(null)}>Back</PreviewButton><PreviewButton className="flex-1" disabled={saving} onClick={confirmOrder}>{saving ? "Confirming…" : "Confirm order"}</PreviewButton></div></div></PreviewBottomSheet> : null}
    {showPlanPicker ? <PreviewBottomSheet title="Choose how you pay" onClose={() => setShowPlanPicker(false)}><div className="space-y-3"><p className="text-sm text-stone-600">This simulation updates the meal balance immediately so each basis is clear before a database exists.</p>{([{ type: "PREPAID", title: "Monthly prepaid", detail: "20 lunches and 10 dinners are loaded now. Eligible cancellations return the meal." }, { type: "COUNT", title: "Flexi count", detail: "20 lunches are available before extra meals are billed." }, { type: "ONE_TIME", title: "Pay as you order", detail: "No meal balance. Every order shows a charge before confirmation." }] as Array<{ type: PlanType; title: string; detail: string }>).map((option) => <PreviewCard key={option.type} className="space-y-2"><h3 className="font-black text-stone-900">{option.title}</h3><p className="text-sm text-stone-600">{option.detail}</p><PreviewButton className="min-h-10 px-3 text-xs" variant={customer.planType === option.type ? "secondary" : "primary"} disabled={customer.planType === option.type} onClick={() => choosePlan(option.type)}>{customer.planType === option.type ? "Current plan" : `Choose ${option.title}`}</PreviewButton></PreviewCard>)}</div></PreviewBottomSheet> : null}
    {showStatement ? <PreviewBottomSheet title="Statement" onClose={() => setShowStatement(false)}><div className="space-y-3"><p className="text-sm text-stone-600">Charges, payments and credits reconcile to the balance shown on your account.</p>{statement.map((entry) => <div key={entry.id} className="flex justify-between gap-3 border-b border-stone-100 pb-2 text-sm"><div><p className="font-bold text-stone-900">{entry.description}</p><p className="text-xs text-stone-500">{formatShortDate(entry.occurredOn)}</p></div><span className={entry.amount < 0 ? "font-black text-emerald-700" : "font-black text-stone-900"}>{entry.amount < 0 ? "−" : "+"}₹{Math.abs(entry.amount)}</span></div>)}<div className="flex justify-between border-t border-stone-200 pt-3 text-base font-black"><span>Balance due</span><span>₹{statementBalance}</span></div>{statementBalance === customer.outstanding ? <PreviewNotice tone="green">Statement reconciled: ₹{statementBalance} due.</PreviewNotice> : <PreviewState kind="error" title="Statement needs attention" detail="The statement and account balance differ in this prototype." />}</div></PreviewBottomSheet> : null}
    {message ? <PreviewToast message={message} onDismiss={() => setMessage(null)} /> : null}{error && !reviewMeal ? <PreviewToast message={error} onDismiss={() => setError(null)} /> : null}
  </div>;
}
