"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

import { Button } from "@/components/ui/button";
import { InputField } from "@/components/ui/field";

type MealType = { id: string; name: string };
type Customer = { id: string; name: string; phone: string; balanceMinor: number };

export function MoneyBoard({ today, mealTypes, customers }: { today: string; mealTypes: MealType[]; customers: Customer[] }) {
  const router = useRouter();
  const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function send(url: string, body: unknown, action: string, success: string) {
    setBusy(action); setMessage(null); setError(null);
    try { const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setError(payload.error ?? "Couldn’t save this account change."); return; } setMessage(success); router.refresh(); }
    catch { setError("Couldn’t reach Heritage Mess. Please try again."); } finally { setBusy(null); }
  }
  function price(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); void send("/api/admin/prices", { mealTypeId: values.get("mealTypeId"), amountMinor: Math.round(Number(values.get("rupees") ?? 0) * 100), effectiveFrom: values.get("effectiveFrom"), effectiveTo: values.get("effectiveTo") || undefined, idempotencyKey: crypto.randomUUID() }, "price", "Price schedule saved."); }
  function payment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); void send("/api/admin/payments", { customerId: values.get("customerId"), amountMinor: Math.round(Number(values.get("rupees") ?? 0) * 100), paymentDate: values.get("paymentDate"), method: values.get("method"), reference: values.get("reference"), note: values.get("note"), idempotencyKey: crypto.randomUUID() }, "payment", "Payment recorded."); }
  return <div className="grid gap-5"><section className="paper-panel rounded-2xl p-5"><p className="utility-type text-[10px] font-bold uppercase tracking-[.1em] text-[var(--muted)]">Money</p><h1 className="mt-1 text-3xl font-black tracking-tight">Pricing and accounts</h1><p className="mt-2 text-sm text-[var(--muted)]">Prices are scheduled by effective date. Account balances come from the real ledger.</p></section>{message ? <p className="rounded-xl bg-[var(--leaf-pale)] px-4 py-3 text-sm font-semibold text-[var(--leaf)]" role="status">{message}</p> : null}{error ? <p className="rounded-xl bg-[var(--danger-pale)] px-4 py-3 text-sm font-semibold text-[var(--danger)]" role="alert">{error}</p> : null}<section className="paper-panel rounded-2xl p-5"><h2 className="text-xl font-black">Schedule a future price</h2><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={price}><label className="grid gap-1 text-sm font-semibold">Meal<select name="mealTypeId" className="min-h-12 rounded-xl border border-[var(--line)] bg-white px-3" required>{mealTypes.map((meal) => <option key={meal.id} value={meal.id}>{meal.name}</option>)}</select></label><InputField label="Price (₹)" name="rupees" type="number" min="0" step="1" required /><InputField label="Effective from" name="effectiveFrom" type="date" defaultValue={today} required /><InputField label="Effective to (optional)" name="effectiveTo" type="date" /><div className="self-end"><Button type="submit" disabled={busy !== null || mealTypes.length === 0}>{busy === "price" ? "Saving…" : "Save price"}</Button></div></form></section><section className="paper-panel rounded-2xl p-5"><h2 className="text-xl font-black">Record payment</h2><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={payment}><label className="grid gap-1 text-sm font-semibold">Customer<select name="customerId" className="min-h-12 rounded-xl border border-[var(--line)] bg-white px-3" required>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name} · balance ₹{customer.balanceMinor / 100}</option>)}</select></label><InputField label="Amount (₹)" name="rupees" type="number" min="1" step="1" required /><InputField label="Payment date" name="paymentDate" type="date" defaultValue={today} required /><label className="grid gap-1 text-sm font-semibold">Method<select name="method" className="min-h-12 rounded-xl border border-[var(--line)] bg-white px-3"><option value="CASH">Cash</option><option value="UPI">UPI</option><option value="BANK_TRANSFER">Bank transfer</option><option value="OTHER">Other</option></select></label><InputField label="Reference (optional)" name="reference" /><InputField label="Note (optional)" name="note" /><div className="self-end"><Button type="submit" disabled={busy !== null || customers.length === 0}>{busy === "payment" ? "Recording…" : "Record payment"}</Button></div></form></section></div>;
}
